require('plugins')
require('core.colorscheme')
require('core.options')
require('core.keymaps')
require('core.autocmds')
require('plugins-config.treesitter')
require('plugins-config.nvim-tree')
require('plugins-config.lualine')
require('plugins-config.gitsigns')
require('plugins-config.lsp')
require('plugins-config.mason')
require('plugins-config.nvim-cmp')
require('plugins-config.ufo')
-- require('plugins-config.copilot')
require("plugins-config.indent-blankline")
-- require("lsp.lua_ls")
